version: '3.8'
services:
 backend:
    build: ./backend
    container_name: backend-NestJs4
    command: npm run start:dev
    restart: always
    volumes:
      - './backend:/app'
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - postgres11
    networks:
      - lb-docker-network

 postgres11:
    image: postgres:11
    container_name: postgres11_3
    restart: unless-stopped
    volumes:
      - ./postgres_db2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - lb-docker-network

networks:
  lb-docker-network:
    driver: bridge